name: pms_external_service_flutter
description: A new Flutter project.
publish_to: 'none' # 不上傳至 pub.dev

environment:
  sdk: '^3.8.0'  # ✅ Dart 3.8 以上

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.6
  shared_preferences: ^2.2.2
  provider: ^6.1.2
  intl: ^0.19.0
  flutter_spinkit: ^5.2.0
  fluttertoast: ^8.2.4
  path_provider: ^2.0.15
  mqtt_client: ^9.8.1 # For MQTT communication

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
